title: Miguel Soares
description: Lead Data Platform Engineer
url: "https://miguelsoaress.github.io"
github_username: miguelsoaress

permalink: /writing/:year/:slug/

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
